---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
script:
  - SIMPLECOV=yes bundle exec $CHECK
rvm:
  - 2.4
  - 2.7
env:
  - CHECK='rubocop'
  - CHECK='rspec spec'
matrix:
  fast_finish: true
branches:
  only:
    - main
    - "/^v\\d/"
    - release
